### PR TITLE
add fixtures

### PR DESCRIPTION
**Pull request by Bilb**
Ready to be merged (and used more globally)

### CODE REVIEW

**Comment by Bilb** [comment]
fixed the conflicts but not ready to be merged. The way to use the fixtures is cumbersome as we need to do something like:
windowA.window.page to access the page item currently.
```ts
    newUser(windowA.window.page, 'Alice'),
  
```

**Comment by Bilb** [comment]
Ready to be merged (and used more globally)

**Review by burtonemily — COMMENTED** [review]
Looks good, just unsure of changing windows to Pages, but other than all fine

**Review by burtonemily — APPROVED** [review]

**Comment by Bilb** [comment]
Closing this in favor of https://github.com/oxen-io/session-playwright/pull/13 (most of this in there, and better)

**Pull request closed without merging**
